package com.xuhailiang5794.business.mapper;

import com.xuhailiang5794.business.entity.IndicatorClassification;
import java.util.List;
import java.util.Map;

public interface IndicatorClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_classification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_classification
     *
     * @mbg.generated
     */
    int insert(IndicatorClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_classification
     *
     * @mbg.generated
     */
    int insertSelective(IndicatorClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_classification
     *
     * @mbg.generated
     */
    IndicatorClassification selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_classification
     *
     * @mbg.generated
     */
    List<IndicatorClassification> selectByCondition(Map<String, Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_classification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndicatorClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ind_indicator_classification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndicatorClassification record);
}